### ISSUE TITLE
Clarify when the module is needed

### ISSUE THREAD

**Issue by tuukkamustonen** [humangeo/multilog#3]
The readme states:

> These file handlers are thread-safe, but not process-safe, so, if you're running a webserver in a **pre-forking** environment

I'm not sure how pre vs post-forking makes difference here. If you fork after loading logging configs into memory, each process will still hold their own copy of handlers etc. and writes are still not properly serialized. If you load configs after forking... well, the result is the same.

@arusahni Care to clarify?

**Comment by dwyerk** [comment]
"These" refers to "Python's built-in loggers" - so in the case of a preforked webserver, you should not use Python's built-in loggers.

**Comment by tuukkamustonen** [comment]
@dwyerk Do you mean it's safe to use them in postfork webserver (e.g. `lazy-apps: true` in uwsgi)?

**Comment by dwyerk** [comment]
The built-in python loggers are not safe to use in any environment which uses multiple processes because the logs can be overwritten. The "pre-forking environment" is used as an example (the next two words in that sentence are "for example") but any other process based model will exhibit the same problems.

**Comment by dwyerk** [comment]
This project was inspired by the Python docs here: https://docs.python.org/3/howto/logging-cookbook.html#a-more-elaborate-multiprocessing-example

**Comment by dwyerk** [comment]
Actually probably this one was the inspiration: https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes

**Comment by tuukkamustonen** [comment]
@dwyerk Ok, I would still remove the "pre-forking environment" from the readme and just replace it with "in multi-process mode" or something like that, as I get impression that the problem is specific to *pre-forking* scenario (even with "for example" following).

Thanks for clarifications!

**Comment by dwyerk** [comment]
@tuukkamustonen you are proof that it's confusing to at least one person so if you want to suggest a rewrite in a merge request we'll be happy to work with you.
