### ISSUE TITLE
Need IP in formatter for log from multi-PC

### ISSUE THREAD

**Issue by zhangli2015** [humangeo/multilog#8]

**Comment by arusahni** [comment]
Multilog only focuses on getting logs from one process to another. Everything beyond that should be just Python.  You should be able to accomplish this via a custom formatter.  [The logging cookbook has a helpful example of how one may include IP addresses](https://docs.python.org/3/howto/logging-cookbook.html#using-filters-to-impart-contextual-information).

**Comment by zhangli2015** [comment]
Thank you, you are right, just the multi-PC use case really needs IP, multilog is often used under this case.
